### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by HankLynch** [escendit/Escendit.Orleans.Streaming.RabbitMQ#2]
Hi, I'm having some issues following the instructions for getting this all wired up.  Is there any chance you could publish a sample project detailing the changes needed?  Something simple like the standard HelloWorld would be fantastic.

**Comment by snovak7** [comment]
Do you have any experience with Orleans? For this to work you need to have Orleans working.

https://learn.microsoft.com/en-us/dotnet/orleans/quickstarts/build-your-first-orleans-app?tabs=visual-studio

When you setup Orleans, then you can follow the README

https://github.com/escendit/Escendit.Orleans.Streaming.RabbitMQ/blob/main/README.md

**Comment by snovak7** [comment]
I've seen you've did some good progress, closing this issue.
